PROCESS BEFORE OUTPUT.
 MODULE STATUS_0300.
*&SPWIZARD: PBO FLOW LOGIC FOR TABSTRIP 'TS_PGI'
  MODULE TS_PGI_ACTIVE_TAB_SET.
  CALL SUBSCREEN TS_PGI_SCA
    INCLUDING G_TS_PGI-PROG G_TS_PGI-SUBSCREEN.

*
PROCESS AFTER INPUT.
  MODULE pai_screen_0300_exit AT EXIT-COMMAND.
*&SPWIZARD: PAI FLOW LOGIC FOR TABSTRIP 'TS_PGI'
  CALL SUBSCREEN TS_PGI_SCA.
  MODULE TS_PGI_ACTIVE_TAB_GET.

   MODULE pai_screen_0300_user.
* MODULE USER_COMMAND_0300.
