PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABSTRIP 'TS_BILLING'
  MODULE TS_BILLING_ACTIVE_TAB_SET.
  CALL SUBSCREEN TS_BILLING_SCA
    INCLUDING G_TS_BILLING-PROG G_TS_BILLING-SUBSCREEN.
* MODULE STATUS_0400.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABSTRIP 'TS_BILLING'
  CALL SUBSCREEN TS_BILLING_SCA.
  MODULE TS_BILLING_ACTIVE_TAB_GET.
* MODULE USER_COMMAND_0400.
