PROCESS BEFORE OUTPUT.
 MODULE STATUS_0120.
 MODULE pbo_0120_modify_screen. " <<< THÊM MỚI
*
PROCESS AFTER INPUT.
 MODULE USER_COMMAND_0120.

 PROCESS ON VALUE-REQUEST.
   FIELD gv_filepath MODULE f4_for_filepath.
