PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABSTRIP 'TS_VALI'
  MODULE TS_VALI_ACTIVE_TAB_SET.
  CALL SUBSCREEN TS_VALI_SCA
    INCLUDING G_TS_VALI-PROG G_TS_VALI-SUBSCREEN.
 MODULE STATUS_0200.

*  MODULE pbo_0200_summary.

PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABSTRIP 'TS_VALI'
  CALL SUBSCREEN TS_VALI_SCA.
  MODULE TS_VALI_ACTIVE_TAB_GET.
 MODULE USER_COMMAND_0200.
