PROCESS BEFORE OUTPUT.
  MODULE status_0700.

  CASE g_current_tab.
    WHEN 'FITEM'.
      CALL SUBSCREEN ssa INCLUDING sy-cprog '0701'.
    WHEN 'FSHIP'.
      CALL SUBSCREEN ssa INCLUDING sy-cprog '0702'.
    WHEN 'FCOND'.
      CALL SUBSCREEN ssa INCLUDING sy-cprog '0703'.
  ENDCASE.
*
PROCESS AFTER INPUT.
 MODULE USER_COMMAND_0700.
